### ISSUE TITLE
properly cite einops

### ISSUE THREAD

**Issue by lucidrains** [deepmind/einshape#1]
this repository clearly was inspired by einops. https://github.com/arogozhnikov/einops

the maintainers of this repository need to cite it properly, now that it has been accepted to ICLR 2022 https://openreview.net/forum?id=oapKSVM2bcj

**Comment by RobertStanforth** [comment]
We thank you for your enquiry.
Our work on this repository was fully independent of einops, and done without any reference to that work.
We therefore do not believe that attribution is required or appropriate.

**Comment by lucidrains** [comment]
wow, no shame. I will be quite public about this, mark my words

**Comment by lucidrains** [comment]
wow, no shame. actually I will escalate this through some emails to your higher ups. let us keep this issue open for now
